### ISSUE TITLE
Missing DLL file required for x64

### ISSUE THREAD

**Issue by pslxc** [Arkueid/Live2DMascot#1]
libcrypto-3-x64 and libssl-3-x64
Here is the DLL file required for x64 that may be missing during error execution, hoping to help your program become more perfect. 
google drive:[DownloadLink](https://drive.google.com/drive/folders/1EB2JayDZcG1YHxvaxp5hSoQ8DzSNPTOm?usp=sharing)

**Comment by Arkueid** [comment]
You remind me that openssl win64 are included in my system PATH, so the app seems to work without the DLLs on my system. It's helpful. Thank you for issuing!
