### ISSUE TITLE
未来还会更新x64的vs工程吗？x64一直无法编译成功。

### ISSUE THREAD

**Issue by yuewenma** [Arkueid/Live2DMascot#13]

**Comment by Arkueid** [comment]
可以，编译失败的情况如果方便也可以提供一下

**Comment by yuewenma** [comment]
> 可以，编译失败的情况如果方便也可以提供一下

5>------ Rebuild All started: Project: Demo, Configuration: CRelease x64 ------
5>AudioUtils.cpp
5>BgmListView.cpp
5>ChatWidget.cpp
5>ControlWidget.cpp
5>Dialog.cpp
5>GLWidget.cpp
5>jsoncpp.cpp
5>LApp.cpp
5>LAppAllocator.cpp
5>LAppDefine.cpp
5>LAppDelegate.cpp
5>LAppLive2DManager.cpp
5>LAppModel.cpp
5>LAppPal.cpp
5>LAppTextureManager.cpp
5>LAppView.cpp
5>LAppWavFileHandler.cpp
5>main.cpp
5>moc_chatwidget.cpp
5>moc_controlwidget.cpp
5>moc_glwidget.cpp
5>NetworkUtils.cpp
5>TouchManager.cpp
5>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(1096,5): error MSB6006: "link.exe" exited with code 1181.
5>LINK : fatal error LNK1181: cannot open input file 'lib\Release\libglew32.lib'
5>Done building project "Demo.vcxproj" -- FAILED.
========== Rebuild All: 4 succeeded, 1 failed, 0 skipped ==========

我猜应该是x64 libglew32.lib这个静态库的问题。
这是我VS链接器Input的配置：
Framework\Release\Framework.lib
glfw\src\Release\glfw3.lib
opengl32.lib
glu32.lib
-NODEFAULTLIB:libcmt.lib
-NODEFAULTLIB:msvcrtd.lib
..\Core\lib\windows\x86_64\143\Live2DCubismCore_MT.lib
lib\Release\libglew32.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib
Qt5Widgets.lib
Qt5Core.lib
Qt5Gui.lib
qtmain.lib
Winmm.lib
libssl.lib
libcrypto.lib
qt5multimedia.lib

**Comment by yuewenma** [comment]
编译通过啦！感谢大佬！写几个目前踩到的坑：
1. LINK : fatal error LNK1181: cannot open input file 'lib\Release\libglew32.lib'
解决：需要把proj_msvc2022_x64_mt\glew\lib\Release中的libglew32.lib放到根目录就能找到了
2. unable to start xxx program xxx is not a valid working directory
解决：需要在VS demo property pages中debugging的Working Directory修改成bin/Demo/Release
3. 编译通过但运行还是报错
解决：将大佬编译好的目录中所有的文件夹和dll复制到bin/Demo/Release里。大力出奇迹！
