### ISSUE TITLE
软件正常运行几次之后就会无法打开，重新下载解压才能继续用

### ISSUE THREAD

**Issue by tonylai000** [Arkueid/Live2DMascot#3]
有时候能正常开关几次，有时候第二次就打不开了。
以下是debug的输出：
QWidget::repaint: Recursive repaint detected
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::fillPath: Painter not active
QPainter::setFont: Painter not active
QPainter::setPen: Painter not active

**Comment by Arkueid** [comment]
这个问题最近几次提交出现过，暂时还没找到原因，我再找找看。

**Comment by Arkueid** [comment]
在我的设备上测试是能够100%成功率启动了，其他环境还没有测试过，大概<del>可能maybe</del>是解决了吧。感谢提交!
