### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by lrioxh** [Arkueid/Live2DMascot#7]
会添加语音输入功能吗，比如按住说话O(∩_∩)O

**Comment by Arkueid** [comment]
可以的，正好最近没有什么想法。但是这方面我没经验，不知道什么时候能做出来(

**Comment by lrioxh** [comment]
正试着自己写一个回头发现大佬已经做出来了哈哈哈

**Comment by Arkueid** [comment]
感谢支持～(∠・ω< )⌒☆
这个可能要等到周末了，最近有点忙，录音功能目前是有些问题的，加上现在的http库不是特别灵活，可能会更换http库，工作量有点大…

**Comment by lrioxh** [comment]
_(:з」∠)_辛苦了！
