### ISSUE TITLE
【求助】关于Resources中的声音来源

### ISSUE THREAD

**Issue by hasban12138** [Arkueid/Live2DMascot#8]
请问Resources中的角色的声音是哪里来的Hiyori有个唱跳rap的这个应该不是原本就有的吧

**Comment by Arkueid** [comment]
Hiyor的语音都是通过[ACGTTS](https://github.com/chinoll/ACGTTS)生成的，类似MoeTTS，文本转语音。Hiyori没有官方语音或者cv，声线属于其他gal角色

**Comment by hasban12138** [comment]
感谢
